# -*- coding: utf-8 -*-
"""firstProj.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rocYiCwAVh_8mhdZJhILdhBuJHWnrso0
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#Read the csv file
df = pd.read_csv("/content/sample_data/ecommerce_customer_data_large.csv")

#size of dataset
df.head

#Data types in dataset
print(df.dtypes)

#size of dataset
print(df.count)

#Number of columns
no_column = len(df.columns)
print(no_column)

#Number of Rows
no_rows = df.shape[0]
print(no_rows)

#summary statistics
df.describe()

